.PHONY: install-frontend lint-frontend test-frontend build-frontend

install-frontend:
	npm install

lint-frontend:
	npm run lint

test-frontend:
	npm run test -- --run

build-frontend:
	npm run build
